### ISSUE TITLE
Select subreddits for the memes or Another source where we can pull JSON data for memes.

### ISSUE THREAD

**Issue by Kynot54** [Kynot54/discord_bot#2]

**Comment by reenell** [comment]
https://www.reddit.com/r/me_irl/
https://www.reddit.com/r/memes/
https://twitter.com/LowResContent

**Comment by Haothai1** [comment]
https://www.reddit.com/r/meme/
https://www.reddit.com/r/dogecoin/
https://twitter.com/WholesomeMeme
https://www.reddit.com/r/HighIQMemes/
https://www.reddit.com/r/MemeEconomy/

**Comment by demihungry** [comment]
https://www.reddit.com/r/dankmemes/
https://www.reddit.com/r/ProgrammerHumor/
https://www.reddit.com/r/memes/comments/doibks/look_at_this_funny_meme_i_found/
https://www.reddit.com/r/Random_Memes/
https://www.reddit.com/r/funnymeme/
